## Simple self attention

In [2]:
import torch

X = torch.tensor([
    [1.0, 0.0, 1.0, 0.0],  # I
    [0.0, 2.0, 0.0, 1.0],  # love
    [1.0, 1.0, 0.0, 2.0]   # cats
])

print(X)
print(X.shape)

tensor([[1., 0., 1., 0.],
        [0., 2., 0., 1.],
        [1., 1., 0., 2.]])
torch.Size([3, 4])


In [12]:
print(X)

tensor([[1., 0., 1., 0.],
        [0., 2., 0., 1.],
        [1., 1., 0., 2.]])


In [3]:
Q = X
K = X
V = X

In [4]:
scores = Q @ K.T

print(scores)

tensor([[2., 0., 1.],
        [0., 5., 4.],
        [1., 4., 6.]])


In [5]:
d_k = K.shape[-1]

scores = scores / torch.sqrt(torch.tensor(d_k))

print(scores)

tensor([[1.0000, 0.0000, 0.5000],
        [0.0000, 2.5000, 2.0000],
        [0.5000, 2.0000, 3.0000]])


In [6]:
attention_weights = torch.softmax(scores, dim=-1)

print(attention_weights)

tensor([[0.5065, 0.1863, 0.3072],
        [0.0486, 0.5922, 0.3592],
        [0.0566, 0.2537, 0.6897]])


In [7]:
output = attention_weights @ V

print(output)

tensor([[0.8137, 0.6798, 0.5065, 0.8007],
        [0.4078, 1.5436, 0.0486, 1.3106],
        [0.7463, 1.1971, 0.0566, 1.6331]])
