
first we need to understand difference between matrices and how do we represent them in numpy. 
and when do we need to use tensor and when do we need use numpy arrays 

what is difference btw dot product and matrix multiplication. 

what is standard deviation 
what is vairance. and intutions behind them. 

we know what is mean,median, mode. 
now we need to know what is the intution behind them. 


suppose a shape of matrix is (2,3) i.e 2 rows and 3 columns 
we can also we have 2 samples. and that sample depends on 3 features/variables.



In [2]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print("\n")
print(A.shape)

[[1 2 3]
 [4 5 6]]


(2, 3)


In [3]:
x = np.array([1, 2, 3])

print(x,"\n")
print(x.shape)

[1 2 3] 

(3,)


so what (3,) mean that means it is a single or 1D numpy array and it has 1 row and 3 columns. generally we can use this for Y matrix thing. 

now the thing what is 3D array ?? is it matrix no. then?

In [6]:
X = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(X,"\n")
print(X.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

(2, 2, 2)


- scalar → 0D
- vector → 1D
- matrix → 2D
- tensor → 3D, 4D, 5D, ...

A PyTorch tensor can:
- perform mathematical operations
- calculate gradients
- run on GPU
- participate in neural-network computation

In [7]:
import torch
x = torch.tensor(5.0, requires_grad=True)

y = x ** 2

y.backward()

print(x.grad)

tensor(10.)


- dot product
it is generally between a scalr and a vector . or 2 vectors
- matrix multiplication 
is 2 matrix multiplication


eg:
- A = [a1,a2,a3] B = [b1,b2,b3]
A.dot(B) -> a1b1+a2b2+a3b3

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.dot(a, b)
print(c)
print(c.shape)

32
()


In [12]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

B = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print("A dot of B \n")
print(A.dot(B))
print(A.dot(B).shape)
print("A @ B \n")
print(A @ B)
print((A @ B).shape)

A dot of B 

[[22 28]
 [49 64]]
(2, 2)
A @ B 

[[22 28]
 [49 64]]
(2, 2)


Variance asks one simple question
"How far are the values from the mean, on average?

Variance measures how spread out the values are around their mean.

suppose you have 1 person data 
age,height,weight
[25, 180, 75]

now take this and put for 100 people

np.array([
    [23,180,74],
    [22,176,70],
    ....
])

now this is 2D thing. 


- now consider 3D thing. 
now you have 10 images and each image is 28 x 28 pixels. 

then example of 4D is like 
color image is not simple 28 X 28 pixel. it has 3 channels. 
Red   → 28 × 28
Green → 28 × 28
Blue  → 28 × 28

so one RGB image is 3 X 28 X 28

now suppose you have 32 images. 
then it is 
  32       3        28     28 
(batch, channels, height, width)

