In [1]:
import numpy as np


X = np.array([
    [1, 2],
    [2, 1],
    [2, 3],
    [3, 2],
    [4, 5],
    [5, 4],
    [5, 6],
    [6, 5]
])


# 2 input features → 4 neurons
W1 = np.random.randn(2, 4)

# One bias for each neuron
b1 = np.zeros(4)


print("X shape:", X.shape)
print("W1 shape:", W1.shape)
print("b1 shape:", b1.shape)

X shape: (8, 2)
W1 shape: (2, 4)
b1 shape: (4,)


In [2]:
Z1 = X @ W1 + b1

print("\nZ1:")
print(Z1)

print("\nZ1 shape:", Z1.shape)


Z1:
[[  2.18911849   4.6920221   -1.48086486  -1.51923692]
 [  3.88940613   3.95115317  -1.92261889  -3.89320592]
 [  4.21529336   7.57308053  -2.61535945  -3.32338453]
 [  5.915581     6.8322116   -3.05711347  -5.69735353]
 [  8.26764311  13.33519737  -4.88434861  -6.93167976]
 [  9.96793074  12.59432845  -5.32610264  -9.30564875]
 [ 10.29381798  16.2162558   -6.0188432   -8.73582737]
 [ 11.99410562  15.47538687  -6.46059722 -11.10979637]]

Z1 shape: (8, 4)


In [3]:
A1 = np.maximum(0, Z1)

print("\nA1:")
print(A1)

print("\nA1 shape:", A1.shape)


A1:
[[ 2.18911849  4.6920221   0.          0.        ]
 [ 3.88940613  3.95115317  0.          0.        ]
 [ 4.21529336  7.57308053  0.          0.        ]
 [ 5.915581    6.8322116   0.          0.        ]
 [ 8.26764311 13.33519737  0.          0.        ]
 [ 9.96793074 12.59432845  0.          0.        ]
 [10.29381798 16.2162558   0.          0.        ]
 [11.99410562 15.47538687  0.          0.        ]]

A1 shape: (8, 4)


In [4]:
# Output layer
W2 = np.random.randn(4, 1)
b2 = np.zeros(1)

Z2 = A1 @ W2 + b2

A2 = 1 / (1 + np.exp(-Z2))

In [5]:
print("\nW2 shape:", W2.shape)
print("b2 shape:", b2.shape)

print("Z2 shape:", Z2.shape)
print("A2 shape:", A2.shape)


W2 shape: (4, 1)
b2 shape: (1,)
Z2 shape: (8, 1)
A2 shape: (8, 1)


## full code

In [6]:
import numpy as np

# ============================================================
# 1. DATASET
# ============================================================

X = np.array([
    [1, 2],
    [2, 1],
    [2, 3],
    [3, 2],
    [4, 5],
    [5, 4],
    [5, 6],
    [6, 5]
])

y = np.array([
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1
])

# Make y shape (8, 1)
y = y.reshape(-1, 1)


# ============================================================
# 2. INITIALIZE PARAMETERS
# ============================================================

# Hidden layer
# Input = 2 features
# Hidden layer = 4 neurons

W1 = np.random.randn(2, 4)
b1 = np.zeros((1, 4))

# Output layer
# Hidden layer = 4 neurons
# Output = 1 neuron

W2 = np.random.randn(4, 1)
b2 = np.zeros((1, 1))


# ============================================================
# 3. ACTIVATION FUNCTIONS
# ============================================================

def relu(z):
    return np.maximum(0, z)


def relu_derivative(z):
    return (z > 0).astype(float)


def sigmoid(z):
    return 1 / (1 + np.exp(-z))


# ============================================================
# 4. TRAINING
# ============================================================

learning_rate = 0.1
epochs = 1000

N = len(X)


for epoch in range(epochs):

    # --------------------------------------------------------
    # FORWARD PROPAGATION
    # --------------------------------------------------------

    # Hidden layer
    Z1 = X @ W1 + b1
    A1 = relu(Z1)

    # Output layer
    Z2 = A1 @ W2 + b2
    A2 = sigmoid(Z2)


    # --------------------------------------------------------
    # LOSS
    # --------------------------------------------------------

    loss = -np.mean(
        y * np.log(A2 + 1e-8) +
        (1 - y) * np.log(1 - A2 + 1e-8)
    )


    # --------------------------------------------------------
    # BACKPROPAGATION
    # --------------------------------------------------------

    # Output layer

    dZ2 = A2 - y

    dW2 = (A1.T @ dZ2) / N

    db2 = np.sum(dZ2, axis=0, keepdims=True) / N


    # Send gradient backwards into hidden layer

    dA1 = dZ2 @ W2.T


    # ReLU derivative

    dZ1 = dA1 * relu_derivative(Z1)

    dW1 = (X.T @ dZ1) / N

    db1 = np.sum(dZ1, axis=0, keepdims=True) / N


    # --------------------------------------------------------
    # UPDATE PARAMETERS
    # --------------------------------------------------------

    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2

    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1


    # --------------------------------------------------------
    # PRINT LOSS
    # --------------------------------------------------------

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")


# ============================================================
# 5. FINAL FORWARD PASS
# ============================================================

Z1 = X @ W1 + b1
A1 = relu(Z1)

Z2 = A1 @ W2 + b2
A2 = sigmoid(Z2)


# ============================================================
# 6. PREDICTIONS
# ============================================================

predictions = (A2 >= 0.5).astype(int)


# ============================================================
# 7. RESULTS
# ============================================================

print("\n--------------------------------")
print("FINAL RESULTS")
print("--------------------------------")

print("\nProbabilities:")
print(A2.flatten())

print("\nPredictions:")
print(predictions.flatten())

print("\nActual:")
print(y.flatten())

print("\nFinal W1:")
print(W1)

print("\nFinal b1:")
print(b1)

print("\nFinal W2:")
print(W2)

print("\nFinal b2:")
print(b2)

Epoch 0, Loss: 5.258971343849935
Epoch 100, Loss: 0.3231944258776232
Epoch 200, Loss: 0.1544362572168857
Epoch 300, Loss: 0.08831327642347798
Epoch 400, Loss: 0.04380869101195434
Epoch 500, Loss: 0.027829300159389767
Epoch 600, Loss: 0.01969057399425556
Epoch 700, Loss: 0.014903165296552664
Epoch 800, Loss: 0.011813611332931831
Epoch 900, Loss: 0.009684390402674178

--------------------------------
FINAL RESULTS
--------------------------------

Probabilities:
[1.72503352e-03 3.14902932e-04 1.93889160e-02 2.03231372e-02
 9.88472922e-01 9.89007340e-01 9.99822955e-01 9.99831253e-01]

Predictions:
[0 0 0 0 1 1 1 1]

Actual:
[0 0 0 0 1 1 1 1]

Final W1:
[[ 0.94557064 -0.33069379 -1.33008055  1.92938115]
 [-0.9566089  -0.49231215 -0.47284556 -0.19915112]]

Final b1:
[[ 2.29084296  0.          0.         -2.25934589]]

Final W2:
[[-2.66391567]
 [ 2.27980719]
 [ 0.8269832 ]
 [ 2.4031853 ]]

Final b2:
[[-2.83590022]]
