### WTF pytorch

In [1]:
import numpy as np
import torch 
import torch.nn as nn

In [2]:
x = np.array([1,2,3])
print(x,"\n")
print(x.shape)

[1 2 3] 

(3,)


In [3]:
x = torch.tensor([1,2,3])
print(x,"\n",x.shape)

tensor([1, 2, 3]) 
 torch.Size([3])


- main thing probably the best thing to remember
- shape means [batch_size, sequence_length , embeddings dimension]

- 32  → batch size
- 128 → sequence length
- 768 → embedding dimension

- 32 sentences
- each sentence has 128 tokens
- each token represented by 768 numbers

In [4]:
matrix = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]
])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])
2
torch.int64


### tensor indexing 

In [13]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [6]:
x[0,0]

tensor(1)

In [7]:
x[1,2]

tensor(7)

In [18]:
# to get entire row
print(x[1,:])
print(x[0,:])

tensor([5, 6, 7, 8])
tensor([1, 2, 3, 4])


In [22]:
# to get entire column
# : means take everthing in that like x[:,1] -> means every row and column 1
print(x[:,1])

tensor([2, 6])


### slicing 

In [19]:
x[:,1:3]

tensor([[2, 3],
        [6, 7]])

In [20]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [23]:
print(x[1, 0],"\n")
print(x[0],"\n")
print(x[:, 2],"\n")
print(x[:, 1:4],"\n")
print(x[:, 1:100],"\n")

tensor(5) 

tensor([1, 2, 3, 4]) 

tensor([3, 7]) 

tensor([[2, 3, 4],
        [6, 7, 8]]) 

tensor([[2, 3, 4],
        [6, 7, 8]]) 



### reshape()

In [24]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(x.shape)

torch.Size([2, 4])


In [27]:
y = x.reshape(4, 2)

print(y)
print(y.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])


- fundamental rule when reshaping no of elements should remain same. 

In [29]:
y = x.reshape(2, -1)
print(y)
print(y.shape)
# what -1 means it is a question mark like 2 * ? = 8. so ? = 4. that what happened here. 

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])


In [31]:
y = x.reshape(-1,8)
print(y)
print(y.shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
torch.Size([1, 8])


### unsqueeze()

In [38]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(x)
print(x.shape)
print(x.ndim)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])
2


In [41]:
y = x.unsqueeze(0)
# we are adding another dimension at position 0
print(y)
print(y.shape)
print(y.ndim)

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])
torch.Size([1, 2, 4])
3


In [42]:
y = x.unsqueeze(1)
# we are adding another dimension at position 1
print(y)
print(y.shape)
print(y.ndim)

tensor([[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]])
torch.Size([2, 1, 4])
3


### sequeeze()

In [43]:
# here we remove the any position that contains dimension as 1
"""
suppose if you are having 
[1,3,1] -> [3]
[2,3,1] -> [2,3]
[3,4] -> [3,4] no effect becasue we are not having dimension 1
"""

'\nsuppose if you are having \n[1,3,1] -> [3]\n[2,3,1] -> [2,3]\n[3,4] -> [3,4] no effect becasue we are not having dimension 1\n'

In [54]:
torch.manual_seed(42)
x_tensor = torch.randint(low = 0, high = 11,size=[1,3,1,2],dtype=torch.int64)
print(x_tensor)
print(x_tensor.shape)
print(x_tensor.ndim)

tensor([[[[ 6,  7]],

         [[ 9,  3]],

         [[ 2, 10]]]])
torch.Size([1, 3, 1, 2])
4


In [45]:
y = x_tensor.squeeze()
print(y)
print(y.shape)
print(y.ndim)

tensor([[ 6,  7],
        [ 9,  3],
        [ 2, 10]])
torch.Size([3, 2])
2


### transpose()

In [49]:
# core thing transpose(0,1) means we are swapping 0 dimension with 1 and 1 dimension with 0
y = x_tensor.transpose(2,3) # means we are swapping 2 and 3 dimensions so output of shape will be [1,3,2,1]
print(y)
print(y.shape)
print(y.ndim)

tensor([[[[ 6],
          [ 7]],

         [[ 9],
          [ 3]],

         [[ 2],
          [10]]]])
torch.Size([1, 3, 2, 1])
4


### permute() 

In [ ]:
# similar to transpose but in transpose we can only shape 2 dimensions but if you change multiple dimensions we use permute()

print(y)
print(y.shape)
print(y.ndim)


tensor([[[[ 6,  9,  2],
          [ 7,  3, 10]]]])
torch.Size([1, 1, 2, 3])
4


### cat()

In [ ]:
# we will concatinate the dimension
y1 = x_tensor.permute(2,0,3,1)
y2 = x_tensor.permute(2,1,3,0)
print(y1.shape,y1.ndim)
print(y2.shape,y2.ndim)
torch.cat(y1,y2)
torch.stack(y1,y2)

torch.Size([1, 1, 2, 3]) 4
torch.Size([1, 3, 2, 1]) 4


### stack()


### broadcasting 


In [55]:
# we compare from rightside and works only if end dimension matches or either is 1
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor([10, 20, 30])

x+b

tensor([[11, 22, 33],
        [14, 25, 36]])

In [56]:
x = torch.tensor([
    [1, 2],
    [3, 4]
])

x + 10

tensor([[11, 12],
        [13, 14]])

### multiplication

In [62]:
torch.manual_seed(42)
A = torch.randint(low = 0, high = 11, size= [2,2],dtype=torch.int64)
B = torch.randint(low = 0, high = 11, size= [2,2],dtype=torch.int64)
print(A,"\n",B)
print(A @ B)
print(A * B)

tensor([[6, 7],
        [9, 3]]) 
 tensor([[ 2, 10],
        [ 3,  0]])
tensor([[33, 60],
        [27, 90]])
tensor([[12, 70],
        [27,  0]])


In [66]:
a = torch.tensor([1,3,4])
b = torch.tensor([[1,3,4],[4,5,6],[7,8,9]])
print(a.shape,b.shape)
print(a,"\n",b)
print(a @ b)
print(a * b)

torch.Size([3]) torch.Size([3, 3])
tensor([1, 3, 4]) 
 tensor([[1, 3, 4],
        [4, 5, 6],
        [7, 8, 9]])
tensor([41, 50, 58])
tensor([[ 1,  9, 16],
        [ 4, 15, 24],
        [ 7, 24, 36]])
