In [1]:
import torch
from torch.utils.data import Dataset

X = torch.tensor([
    [1., 2.],
    [3., 4.],
    [5., 6.],
    [7., 8.],
    [9., 10.]
])

y = torch.tensor([0, 1, 0, 1, 0])

In [2]:
class MyDataset(Dataset):

    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [3]:
dataset = MyDataset(X, y)

In [4]:
len(dataset)

5

In [5]:
dataset[3]

(tensor([7., 8.]), tensor(1))

In [6]:
from torch.utils.data import DataLoader

loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

In [7]:
for X_batch, y_batch in loader:
    print(X_batch)
    print(y_batch)

tensor([[ 9., 10.],
        [ 5.,  6.]])
tensor([0, 0])
tensor([[7., 8.],
        [1., 2.]])
tensor([1, 0])
tensor([[3., 4.]])
tensor([1])
