In [18]:
import numpy as np

X = np.array([
    [1, 2],
    [2, 1],
    [2, 3],
    [3, 2],
    [4, 5],
    [5, 4],
    [5, 6],
    [6, 5]
])

y = np.array([
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1
])

print("X:")
print(X)

print("\ny:")
print(y)

print("\nX shape:", X.shape)
print("y shape:", y.shape)

X:
[[1 2]
 [2 1]
 [2 3]
 [3 2]
 [4 5]
 [5 4]
 [5 6]
 [6 5]]

y:
[0 0 0 0 1 1 1 1]

X shape: (8, 2)
y shape: (8,)


In [2]:
import numpy as np

# One training example
x = np.array([2, 3])

# Initial weights
W = np.array([0.5, 0.8])

# Bias
b = 0.1

# Weighted sum
z = np.dot(x, W) + b

print("x:", x)
print("W:", W)
print("b:", b)
print("z:", z)

x: [2 3]
W: [0.5 0.8]
b: 0.1
z: 3.5000000000000004


In [3]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

a = sigmoid(z)
print("activation:", a)


activation: 0.9706877692486436


In [ ]:
# A = np.random.rand(3, 2)   # 3 stacked 2x2 matrices
# B = np.random.rand(5, 3, 2)
# print(A)
# print(A.shape)
# print("******")
# print(B)
# print(B.shape)

In [19]:
import numpy as np


# Dataset
X = np.array([
    [1, 2],
    [2, 1],
    [2, 3],
    [3, 2],
    [4, 5],
    [5, 4],
    [5, 6],
    [6, 5]
])

y = np.array([
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1
])


# Weights
W = np.array([0.5, 0.8])

# Bias
b = 0.1


# Forward pass
z = X @ W + b


print("X shape:", X.shape)
print("W shape:", W.shape)

print("\nz:")
print(z)

X shape: (8, 2)
W shape: (2,)

z:
[2.2 1.9 3.5 3.2 6.1 5.8 7.4 7.1]


In [20]:
a = sigmoid(z)
print(a)

[0.90024951 0.86989153 0.97068777 0.96083428 0.99776215 0.99698158
 0.99938912 0.99917558]


In [21]:
predictions = (a >= 0.5).astype(int)

print("\npredictions:")
print(predictions)

print("\nactual:")
print(y)


predictions:
[1 1 1 1 1 1 1 1]

actual:
[0 0 0 0 1 1 1 1]


In [22]:
loss = - np.mean(y*np.log(a)+ (1-y)*np.log(1-a))
print(loss)

1.3901091246746708


In [25]:
dz = a-y
dW = (X.T @ dz) / len(X)
db = np.mean(dz)

print("\ndz:")
print(dz)

print("\ndW:")
print(dW)


print("\ndb:")
print(db)


dz:
[ 9.00249511e-01  8.69891526e-01  9.70687769e-01  9.60834277e-01
 -2.23784852e-03 -3.01841632e-03 -6.10879359e-04 -8.24424686e-04]

dW:
[0.92898331 0.93413401]

db:
0.46187143925967233


In [26]:
learning_rate = 0.1

W = W - learning_rate * dW
b = b - learning_rate * db

In [27]:
print("\nUpdated W:")
print(W)

print("\nUpdated b:")
print(b)


Updated W:
[0.40710167 0.7065866 ]

Updated b:
0.05381285607403277


In [28]:
z = X @ W + b
a = sigmoid(z)

new_loss = -np.mean(
    y * np.log(a) +
    (1 - y) * np.log(1 - a)
)

print("\nNew loss:", new_loss)


New loss: 1.1984539236511358


In [29]:
import numpy as np


X = np.array([
    [1, 2],
    [2, 1],
    [2, 3],
    [3, 2],
    [4, 5],
    [5, 4],
    [5, 6],
    [6, 5]
])

y = np.array([
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1
])


W = np.array([0.5, 0.8])
b = 0.1

learning_rate = 0.1


def sigmoid(z):
    return 1 / (1 + np.exp(-z))


# ---------- FORWARD PASS ----------

z = X @ W + b
a = sigmoid(z)


# ---------- LOSS ----------

loss = -np.mean(
    y * np.log(a) +
    (1 - y) * np.log(1 - a)
)


# ---------- GRADIENTS ----------

dz = a - y

dW = (X.T @ dz) / len(X)
db = np.mean(dz)


print("Old loss:", loss)
print("Old W:", W)
print("Old b:", b)

print("\ndW:", dW)
print("db:", db)


# ---------- UPDATE ----------

W = W - learning_rate * dW
b = b - learning_rate * db


# ---------- FORWARD PASS AGAIN ----------

z = X @ W + b
a = sigmoid(z)


# ---------- NEW LOSS ----------

new_loss = -np.mean(
    y * np.log(a) +
    (1 - y) * np.log(1 - a)
)


print("\nUpdated W:", W)
print("Updated b:", b)
print("New loss:", new_loss)

Old loss: 1.3901091246746708
Old W: [0.5 0.8]
Old b: 0.1

dW: [0.92898331 0.93413401]
db: 0.46187143925967233

Updated W: [0.40710167 0.7065866 ]
Updated b: 0.05381285607403277
New loss: 1.1984539236511358


In [30]:
learning_rate = 0.1
epochs = 1000

for epoch in range(epochs):

    # Forward pass
    z = X @ W + b
    a = sigmoid(z)

    # Loss
    loss = -np.mean(
        y * np.log(a) +
        (1 - y) * np.log(1 - a)
    )

    # Gradients
    dz = a - y

    dW = (X.T @ dz) / len(X)
    db = np.mean(dz)

    # Update parameters
    W = W - learning_rate * dW
    b = b - learning_rate * db

    # Print progress
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")

Epoch 0, Loss: 1.1984539236511358
Epoch 100, Loss: 0.3863002798180945
Epoch 200, Loss: 0.2789168835087911
Epoch 300, Loss: 0.218128693239406
Epoch 400, Loss: 0.17955739594608555
Epoch 500, Loss: 0.15298049157985483
Epoch 600, Loss: 0.13354632009959658
Epoch 700, Loss: 0.11869545618437971
Epoch 800, Loss: 0.10695931990745518
Epoch 900, Loss: 0.09743728429611825


In [31]:
print("\nFinal W:", W)
print("Final b:", b)


Final W: [0.92779659 0.9284381 ]
Final b: -6.124085901038267


In [32]:
# Final forward pass
z = X @ W + b
a = sigmoid(z)

# Convert probabilities to classes
predictions = (a >= 0.5).astype(int)

print("\nProbabilities:")
print(a)

print("\nPredictions:")
print(predictions)

print("\nActual:")
print(y)


Probabilities:
[0.03424356 0.03422235 0.18494782 0.18485113 0.90284918 0.9027929
 0.98346375 0.98345331]

Predictions:
[0 0 0 0 1 1 1 1]

Actual:
[0 0 0 0 1 1 1 1]
